version: '3.7'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - feature_flags_network

  backend:
    build: ./backend
    ports:
      - 8080:8080
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://root:root@mongo:27017
      DATABASE_NAME: feature_flags
    volumes:
      - .:/usr/src/app
    networks:
      - feature_flags_network

  frontend:
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
    networks:
      - feature_flags_network

networks:
  feature_flags_network:
    name: feature_flags_network
