version: '3.7'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - feature-flags-network

  feature-flags-service:
    image: thisk8brd/feature-flags-service
    container_name: feature-flags-service
    build: ./backend
    ports:
      - 8080:8080
    depends_on:
      - mongo
    environment:
      MONGODB_URI: ${MONGODB_URI}
      DATABASE_NAME: ${DATABASE_NAME}
    volumes:
      - .:/usr/src/app
    networks:
      - feature-flags-network

  feature-flags-app:
    image: thisk8brd/feature-flags-app
    container_name: feature-flags-app
    build: ./frontend
    ports:
      - 5173:80
    depends_on:
      - feature-flags-service
    volumes:
      - ./frontend:/usr/src/app
    environment:
      VITE_API_URL: ${VITE_API_URL}
    networks:
      - feature-flags-network

networks:
  feature-flags-network:
    name: feature-flags-network
